export const DEFAULT_PALETTE: Themes.Palette = {
    "text": "#333333",
    "text-active": "#050505",
    "text-disabled": "#b3b3b3",
    "borders": "#e2e2e2",
    "bg-panel": "#ffffff",
    "bg-panel-hover": "#daebf7",
    "bg-toolbar": "#2c2c2c",
    "bg-toolbar-hover": "#000000",
    "bg-toolbar-active": "#18a0fb",
    "fg-toolbar": "#ffffff",
    "fg-toolbar-hover": "#ffffff",
    "fg-toolbar-active": "#ffffff",
    "fg-toolbar-disabled": "#b3b3b3",
    "fg-toolbar-filename": "#ffffff",
    "fg-toolbar-foldername": "#aaaaaa",
    "fg-toolbar-chevron": "#ffffff",
    "fg-toolbar-unsavedicon": "#a1a1a1",
    "fg-toolbar-login-button": "#ffffff",
    "fg-toolbar-login-button-border": "#d3d3d3",
    "fg-toolbar-login-button-active": "#808080",
    "bg-overlay": "#222222",
    "fg-overlay": "#ffffff",
    "bg-overlay-outline": "#292828",
    "bg-overlay-inner-outline": "#000000",
    "bg-tab": "#222222",
    "bg-tab-hover": "#2c2c2c",
    "bg-tab-active": "#2c2c2c",
    "fg-tab": "#ffffff",
    "fg-tab-hover": "#ffffff",
    "fg-tab-active": "#ffffff",
    "bg-header": "#222222",
    "fg-header": "#ffffff",
    "bg-header-control": "#222222",
    "bg-header-control-hover": "#2c2c2c",
    "bg-header-control-active": "#2c2c2c",
    "fg-header-control": "#ffffff",
    "fg-header-control-hover": "#ffffff",
    "fg-header-control-active": "#ffffff",
    "fg-component": "#7b61ff",
    "fg-component-disabled": "#4e428a",
    "fg-component-disabled-row-active": "#bfbafc",
    "bg-window-close": "#e81123",
    "bg-beta-label": "#1bc47d",
};

export const DEFAULT_THEME = {
    name: "Default Theme",
    author: "Figma",
    id: "0",
    palette: DEFAULT_PALETTE,
};
